/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bravaislattices;

/**
 *
 * @author eeccm
 */
public class BravaisLattices extends javax.swing.JFrame {

    /**
     * Creates new form ElectromagneticSpectrum
     */
    public BravaisLattices() {
        initComponents();
        painelAnswer.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sliderAlpha = new javax.swing.JSlider();
        sliderGama = new javax.swing.JSlider();
        sliderBeta = new javax.swing.JSlider();
        labelAlpha = new javax.swing.JLabel();
        labelBeta = new javax.swing.JLabel();
        labelA3 = new javax.swing.JLabel();
        sliderA1 = new javax.swing.JSlider();
        sliderA2 = new javax.swing.JSlider();
        sliderA3 = new javax.swing.JSlider();
        labelGama1 = new javax.swing.JLabel();
        labelA1 = new javax.swing.JLabel();
        labelA2 = new javax.swing.JLabel();
        painelAnswer = new javax.swing.JPanel();
        labelAnswer = new javax.swing.JLabel();
        lblimage = new javax.swing.JLabel();
        labelStringalpha = new javax.swing.JLabel();
        labelStringbeta = new javax.swing.JLabel();
        labelStringgama = new javax.swing.JLabel();
        labelStringa1 = new javax.swing.JLabel();
        labelStringa2 = new javax.swing.JLabel();
        labelStringa3 = new javax.swing.JLabel();
        buttonType = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sliderAlpha.setMaximum(360);
        sliderAlpha.setValue(90);
        sliderAlpha.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderAlphaStateChanged(evt);
            }
        });

        sliderGama.setMaximum(360);
        sliderGama.setToolTipText("");
        sliderGama.setValue(90);
        sliderGama.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderGamaStateChanged(evt);
            }
        });

        sliderBeta.setMaximum(360);
        sliderBeta.setValue(90);
        sliderBeta.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderBetaStateChanged(evt);
            }
        });

        labelAlpha.setText("α");

        labelBeta.setText("β");

        labelA3.setText("a3");

        sliderA1.setMaximum(360);
        sliderA1.setValue(0);
        sliderA1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderA1StateChanged(evt);
            }
        });

        sliderA2.setMaximum(360);
        sliderA2.setValue(0);
        sliderA2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderA2StateChanged(evt);
            }
        });

        sliderA3.setMaximum(360);
        sliderA3.setValue(0);
        sliderA3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderA3StateChanged(evt);
            }
        });

        labelGama1.setText("γ");

        labelA1.setText("a1");

        labelA2.setText("a2");

        labelAnswer.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelAnswer.setForeground(new java.awt.Color(204, 51, 0));
        labelAnswer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAnswer.setText("-");
        labelAnswer.setToolTipText("");
        labelAnswer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CondensedMatterIcons/CondensedMatterImages.png"))); // NOI18N

        javax.swing.GroupLayout painelAnswerLayout = new javax.swing.GroupLayout(painelAnswer);
        painelAnswer.setLayout(painelAnswerLayout);
        painelAnswerLayout.setHorizontalGroup(
            painelAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelAnswerLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        painelAnswerLayout.setVerticalGroup(
            painelAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAnswerLayout.createSequentialGroup()
                .addGroup(painelAnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelAnswerLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelAnswerLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(labelAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        labelStringalpha.setText("90");

        labelStringbeta.setText("90");

        labelStringgama.setText("90");

        labelStringa1.setText("0");

        labelStringa2.setText("0");

        labelStringa3.setText("0");

        buttonType.setText("What type of bravais lattices parameters :");
        buttonType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(labelAlpha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelBeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(labelGama1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sliderAlpha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sliderBeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sliderGama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelA1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sliderA1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelA2)
                                    .addComponent(labelA3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sliderA3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sliderA2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelStringalpha)
                            .addComponent(labelStringbeta)
                            .addComponent(labelStringgama)
                            .addComponent(labelStringa1)
                            .addComponent(labelStringa2)
                            .addComponent(labelStringa3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(painelAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(buttonType)))
                        .addGap(0, 42, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sliderAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAlpha))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelStringalpha)
                        .addGap(30, 30, 30)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelStringbeta)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelBeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sliderBeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderGama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelGama1)
                    .addComponent(labelStringgama))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelA1)
                    .addComponent(sliderA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStringa1))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelA2)
                    .addComponent(sliderA2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStringa2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderA3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelA3)
                    .addComponent(labelStringa3))
                .addGap(32, 32, 32)
                .addComponent(buttonType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(697, 750));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTypeActionPerformed
        // TODO add your handling code here:
        painelAnswer.setVisible(true);
        int alpha = (Integer) sliderAlpha.getValue();        
        int beta = (Integer) sliderBeta.getValue();
        int gama = (Integer) sliderGama.getValue(); 
        int a1 = (Integer) sliderA1.getValue();
        int a2 = (Integer) sliderA2.getValue() ; 
        int a3 =(Integer) sliderA3.getValue() ;
        
                
        if (alpha==90&&beta==90&&gama==90){
            if (a1==a2&&a2==a3){
            labelAnswer.setText("Cubic");         
            lblimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CondensedMatterIcons/Cubic.png")));
            }
            else if (a1==a2&&a2!=a3) {
            labelAnswer.setText("Tetragonal");
            lblimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CondensedMatterIcons/Tetragonal.png")));
            }
            else if (a1!=a2&&a2!=a3&&a1!=a3) {
            labelAnswer.setText("Orthorombic");
            lblimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CondensedMatterIcons/Orthorombic.png")));
            }        
        }
          else if (alpha==90&&beta==90&&gama!=90){
            if (a1==a2&&a2==a3){
            labelAnswer.setText("<html>Rhombohedral or Trigonal<html>");
            lblimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CondensedMatterIcons/CondensedMatterImages.png")));
            }
            else if (a1==a2&&a2!=a3){
            labelAnswer.setText("Hexagonal");
            lblimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CondensedMatterIcons/Hexagonal.png")));
            }
            else if (a1!=a2&&a2!=a3){
            labelAnswer.setText("Monoclinic");
            lblimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CondensedMatterIcons/Monoclinic.png")));
            }
          }
        else if (alpha!=beta&&gama!=90){
            labelAnswer.setText("Triclinic");
            lblimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CondensedMatterIcons/Triclinic.png")));
            }
    }//GEN-LAST:event_buttonTypeActionPerformed

    private void sliderA3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderA3StateChanged
        // TODO add your handling code here:
        labelStringa3.setText(Integer.toString(sliderA3.getValue()));
    }//GEN-LAST:event_sliderA3StateChanged

    private void sliderA2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderA2StateChanged
        // TODO add your handling code here:
        labelStringa2.setText(Integer.toString(sliderA2.getValue()));
    }//GEN-LAST:event_sliderA2StateChanged

    private void sliderA1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderA1StateChanged
        // TODO add your handling code here:        
        labelStringa1.setText(Integer.toString(sliderA1.getValue()));
    }//GEN-LAST:event_sliderA1StateChanged

    private void sliderGamaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderGamaStateChanged
        // TODO add your handling code here:        
        labelStringgama.setText(Integer.toString(sliderGama.getValue()));
    }//GEN-LAST:event_sliderGamaStateChanged

    private void sliderBetaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderBetaStateChanged
        // TODO add your handling code here:       
        labelStringbeta.setText(Integer.toString(sliderBeta.getValue()));
    }//GEN-LAST:event_sliderBetaStateChanged

    private void sliderAlphaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderAlphaStateChanged
        // TODO add your handling code here:
        labelStringalpha.setText(Integer.toString(sliderAlpha.getValue()));
    }//GEN-LAST:event_sliderAlphaStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BravaisLattices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BravaisLattices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BravaisLattices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BravaisLattices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BravaisLattices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelA1;
    private javax.swing.JLabel labelA2;
    private javax.swing.JLabel labelA3;
    private javax.swing.JLabel labelAlpha;
    private javax.swing.JLabel labelAnswer;
    private javax.swing.JLabel labelBeta;
    private javax.swing.JLabel labelGama1;
    private javax.swing.JLabel labelStringa1;
    private javax.swing.JLabel labelStringa2;
    private javax.swing.JLabel labelStringa3;
    private javax.swing.JLabel labelStringalpha;
    private javax.swing.JLabel labelStringbeta;
    private javax.swing.JLabel labelStringgama;
    private javax.swing.JLabel lblimage;
    private javax.swing.JPanel painelAnswer;
    private javax.swing.JSlider sliderA1;
    private javax.swing.JSlider sliderA2;
    private javax.swing.JSlider sliderA3;
    private javax.swing.JSlider sliderAlpha;
    private javax.swing.JSlider sliderBeta;
    private javax.swing.JSlider sliderGama;
    // End of variables declaration//GEN-END:variables
}
